### ISSUE TITLE
Catchpoint blog migration

### ISSUE THREAD

**Issue by doffymingozzz** [TiTi/jswtf#2]
Hi!

It’s Gleb from Catchpoint.com.

I've noticed that your website links to our old blog, which we’re currently migrating from a subdomain to the main domain. The reason I’m reaching out is to make sure you won’t have a 404 error on your website.

You have a link to our old blog on the following pages
I wonder if you’d be able to replace it with the new one:
https://titi.github.io/links/feed-71/ - https://www.catchpoint.com/blog/web-performance-is-not-an-it-thing-only
https://titi.github.io/links/feed-79/ - https://www.catchpoint.com/blog/performance-culture
Thanks for linking to Catchpoint.com!

Please don’t hesitate to contact me if something comes up v-gkapusto@catchpoint.com!

Best, 
Gleb

**Comment by TiTi** [comment]
Hello,

I made the change.

Note: the proper repository for the issue should have been https://github.com/TiTi/titi.github.io
